# Generated by Django 5.2.6 on 2025-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_rider_wallet_balance_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
