# Generated by Django 5.2.6 on 2025-10-27 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rider_current_latitude_rider_current_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('scooter', 'Scooter')], max_length=20),
        ),
        migrations.CreateModel(
            name='RiderKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('national_id_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('scooter', 'Scooter')], max_length=20)),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=100)),
                ('drivers_license_number', models.CharField(max_length=100, unique=True)),
                ('license_issue_date', models.DateField()),
                ('license_expiry_date', models.DateField()),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=32)),
                ('drivers_license_document', models.FileField(blank=True, upload_to='kyc/rider/drivers_license/')),
                ('vehicle_registration_document', models.FileField(blank=True, upload_to='kyc/rider/vehicle_registration/')),
                ('insurance_document', models.FileField(blank=True, upload_to='kyc/rider/insurance/')),
                ('national_id_document', models.FileField(blank=True, upload_to='kyc/rider/national_id/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rider_kycs', to=settings.AUTH_USER_MODEL)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='accounts.rider')),
            ],
        ),
        migrations.CreateModel(
            name='VendorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('national_id_number', models.CharField(max_length=100, unique=True)),
                ('business_registration_number', models.CharField(max_length=100)),
                ('tax_id_number', models.CharField(blank=True, max_length=100)),
                ('business_address', models.TextField()),
                ('business_phone', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_routing_number', models.CharField(blank=True, max_length=100)),
                ('national_id_document', models.FileField(blank=True, upload_to='kyc/national_id/')),
                ('business_registration_document', models.FileField(blank=True, upload_to='kyc/business_registration/')),
                ('tax_document', models.FileField(blank=True, upload_to='kyc/tax/')),
                ('bank_statement', models.FileField(blank=True, upload_to='kyc/bank_statement/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='accounts.vendor')),
            ],
        ),
    ]
